config/routes.rb
Juggernaut::Application.routes.draw do
  match '/api/annotations/s3_store' => 'api/annotations#s3_store'
  
  namespace :api do
    resources :users
    resources :tasks
    resources :subjects do
      collection do
        get :next_subject_for_workflow
        get :next_subject_for_classification
        get :get_image_for_battle
      end
    end
    
    resources :classifications
    resources :annotations
    resources :favourites
  end
  
  namespace :public do
    resources :users do
      resources :classifications
      resources :favourites
    end
    
    resources :classifications
    resources :favourites
    resources :subjects
  end
  
  resources :dashboard
  
  match '/classify' => 'workflows#classify', :as => :classify
  match '/classify/:id' => 'workflows#classify'
  match '/next_task_or_end/:id' => 'workflows#next_task_or_end'
  match '/add_favourites' => 'workflows#add_favourites', :as => :add_favourite
  match '/rewind/:id' => 'workflows#rewind'
  match '/logout' => 'application#cas_logout'
  
  match '/profile' => 'home#profile', :as => :profile
  match '/toggle_api' => 'home#toggle_api'
  root :to => 'home#index'
end

app/models/result.rb
class Result < ActiveRecord::Base
  has_many :result_subjects, :dependent => :destroy
  has_many :subjects, :through => :result_subjects
  
  validates_presence_of :value
end

app/models/subject.rb
class Subject < ActiveRecord::Base
  attr_accessor :upload_errors
  
  has_many :subject_classifications
  has_many :classifications, :through => :subject_classifications
  has_many :favourites
  has_many :result_subjects
  has_many :results, :through => :result_subjects
  has_many :groups, :as => :focus
  
  validates_presence_of :name
  
  scope :recent, lambda { |*args| order('created_at desc').where('created_at > ?', args.first || SiteConfig.subject_timeframe) }
  scope :active, lambda { where(:active => true) }
  
  KNOWN_FILE_TYPES = ['application/pdf',
  'text/plain',
  'application/zip',
  'application/x-compressed',
  'application/x-zip-compressed',
  'multipart/x-zip',
  'applcation/x-tar',
  'application/x-gzip',
  'image/jpeg',
  'image/gif',
  'image/png']
  
  def update_classification_count
    Subject.increment_counter(:classification_count, id)
  end
  
  # cache all subjects (only works for a limited number with Memcache (~30,000) because of 1MB limit)
  def self.cached_subjects
    Rails.cache.fetch('all-subjects') { all }
  end
  
  def self.cached_count
    Rails.cache.fetch('subject-count') { count }
  end
  
  def self.cached_subjects_for_workflow(workflow_id)
    Rails.cache.fetch("all-subjects-task-#{ workflow_id }") { where(:workflow_id => workflow_id).all }
  end
  
  def self.cached_count_for_workflow(workflow_id)
    Rails.cache.fetch("subject-count-task-#{ workflow_id }") { count(:all, :conditions => { :workflow_id => workflow_id }) }
  end
  
  def self.next_for_classification
    # currently returns a random subject
    [ cached_subjects[rand(cached_count)] ]
  end
  
  def self.next_for_workflow(workflow_id)
    count = cached_count_for_workflow(workflow_id)
    [ cached_subjects_for_workflow(workflow_id)[rand(count)] ]
  end
  
  # This method is finding the ids of all of the subjects that the user has classified so far and then doing
  # select to find the first one that they haven't seen.
  def self.next_original_for_user(user)
    recents = joins(:classifications).where(:classifications => { :zooniverse_user_id => user.id }).select('subjects.id').all
    if recents.any?
      where(['id NOT IN (?)', recents]).first
    else
      first
    end
  end
  
  def self.supported_content_type?(incoming)
    incoming ? KNOWN_FILE_TYPES.include?(File.mime_type?(incoming).split(';').first) : false
  end
  
  def self.create_and_upload(incoming)
    create(incoming[:subject]).tap do |subject|
      subject.upload_errors = []
      subject.upload_errors << 'Invalid content type' unless supported_content_type?(incoming[:file])
      
      unless subject.upload_errors.any?
        subject.upload_errors << 'Upload failed' unless S3Uploader.upload_subject(incoming[:file], subject)
      end
      
      subject.destroy if subject.upload_errors.any?
    end
  end
end

app/models/workflow.rb
class Workflow < ActiveRecord::Base
  has_many :workflow_tasks
  has_many :classifications
  
  validates_uniqueness_of :name
  
  def self.default
    where(:default => true).first
  end
  
  def tasks
    workflow_tasks
  end
  
  def starting_task
    WorkflowTask.first :conditions => { :workflow_id => id, :parent_id => nil }
  end
end

app/controllers/workflows_controller.rb
class WorkflowsController < ApplicationController
  skip_before_filter :login_required
  skip_before_filter :login_from_cookie
  before_filter CASClient::Frameworks::Rails::GatewayFilter, :only => :classify
  before_filter :check_or_create_zooniverse_user, :only => :classify
  respond_to :html
  respond_to :js, :only => [:next_task_or_end, :rewind, :add_favourites]
  
  def classify
    if active_session?
      workflow_task_id = session[:current_workflow_task_id]
      @workflow_task = WorkflowTask.find(workflow_task_id)
    else #user is starting the workflow
      if params[:id]
        @workflow_task = Workflow.find(params[:id]).starting_task
      else
        @workflow_task = Workflow.default.starting_task
      end
    end
    
    @workflow = @workflow_task.workflow
    
    # Warning, assigning two variables here
    assign_current_or_next_subjects_for_classification(@workflow)
    
    unless zooniverse_user
      flash[:warning] = t 'workflows.controllers.not_logged_in'
    end
  end
  
  def next_task_or_end
    workflow_answer = WorkflowAnswer.find(params[:id])
    subject_ids = session[:current_subject_ids]
    build_result([subject_ids], workflow_answer)
    
    if workflow_answer.ends_workflow?
      if zooniverse_user
        Classification.create_with_subjects_and_annotations(classification_from_result)
      else
        flash[:warning] = t 'workflows.controllers.not_logged_in'
      end
      reset_workflow_session # we're done here so clear out old classification history
    else
      @workflow_task = WorkflowTask.find(workflow_answer.next_workflow_task_id)
      session[:current_workflow_task_id] = @workflow_task.id
    end
  end
  
  def rewind
    if valid_results_session?
      begin
        rewind_to_task_id = params[:id].to_i
        session[:result].each_with_index do |result, index|
          if result[:workflow_task_id].to_i == rewind_to_task_id
            @position = index
          end
        end
        
        new_session = session[:result].slice(0, @position)
        
        @workflow_task = WorkflowTask.find(params[:id])
        session[:current_workflow_task_id] = @workflow_task.id
        session[:result] = new_session
      rescue
        reset_workflow_session # session is invalid, reset everything and start again
        flash[:notice] = t 'workflows.controllers.problem'
        redirect_to :action => "classify"
      end
    else
      reset_workflow_session # session is invalid, reset everything and start again
      flash[:notice] = t 'workflows.controllers.problem'
      redirect_to :action => "classify"
    end
  end
  
  def classification_from_result
    begin
      results = session[:result]
      subjects = results.first[:subjects]
      started = session[:started]
      ended = Time.now.utc
      
      posted_subjects = []
      subjects.each do |subject|
        posted_subjects << { :id => subject }
      end
      
      posted_annotations = []
      results.each do |result|
        posted_annotations << { :task_id => result[:task_id], :answer_id => result[:answer_id] }
      end
      
      workflow_id = session[:current_workflow_id]
      posted = { :started => started, :ended => ended, :locale => 'en', :workflow_id => workflow_id, :zooniverse_user_id => zooniverse_user_id, :subjects => posted_subjects, :annotations => posted_annotations }
    rescue
      posted = nil
    end
    posted
  end
  
  def add_favourites
    return unless current_zooniverse_user && session[:current_subject_ids]
    session[:current_subject_ids].each do |subject_id|
      current_zooniverse_user.favourites.find_or_create_by_subject_id(:subject_id => subject_id)
    end
    
    render :nothing => true
  end
  
  def reset_workflow_session
    session[:current_workflow_id] = nil
    session[:current_workflow_task_id] = nil
    session[:current_subject_ids] = nil
    session[:current_subject_locations] = nil
    session[:result] = nil
    session[:started] = nil
  end
  
  def assign_current_or_next_subjects_for_classification(workflow)
    unless session[:current_subject_ids] && session[:current_subject_locations]
      # Get new selection of subjects for classification if we don't already have them
      subjects = Subject.next_for_classification
      session[:current_subject_ids] = subjects.collect { |a| a.id }
      session[:current_subject_locations] = subjects.collect { |a| a.location }
      session[:current_workflow_id] = workflow.id
      session[:started] = Time.now.utc
    end
  end
  
  def valid_results_session?
    session_valid?(session[:result])
  end
  
  def active_session?
    session[:current_workflow_task_id].nil? ? false : true
  end
  
  def build_result(subjects, workflow_answer)
    initialize_results
    session[:result].push({ :subjects => subjects,
                            :workflow_answer_id => workflow_answer.id,
                            :answer_id => workflow_answer.answer.id,
                            :workflow_task_id => workflow_answer.workflow_task.id,
                            :task_id => workflow_answer.workflow_task.task.id })
  end
  
  def initialize_results
    if session[:result]
      session[:result]
    else
      session[:result] = []
    end
  end
end

app/helpers/workflows_helper.rb
module WorkflowsHelper
end

app/views/workflows/_answers.html.erb
<ul>
<%- @workflow_task.answers.each do |a| -%>
	<li><%= link_to a.value, {:controller => "workflows", :action => "next_task_or_end", :id => a.id}, {:remote => true}  %></li>
<%- end -%>
</ul>

app/views/workflows/_favourite.html.erb
<%- subject_ids = session[:current_subject_ids] %>
<%- unless current_zooniverse_user.favourite_ids & subject_ids == subject_ids %>
  <%= link_to t('workflows.views.add_favourite'), add_favourite_path, { :remote => true, :onclick => "$(this).parent().html('<p>#{ t('workflows.views.favourited') }</p>')" } %>
<% end -%>

app/views/workflows/_history.html.erb
<%- if @workflow_task.has_ancestors? -%>	
<p><%= t 'workflows.views.history.heading' %></p>

	<%- @workflow_task.ancestors.reverse.each_with_index do |task, index| -%>
		<%= link_to "#{t 'workflows.views.history.rewind_link'}", {:controller => "workflows", :action => "rewind", :id => task.id}, {:remote => true, :title => "#{ task.name }"} %> <%- unless index == @workflow_task.ancestors.size-1 -%>&middot;<%- end -%>		
	<%- end -%>
<%- end -%>

app/views/workflows/_question.html.erb
<%= @workflow_task.name %> <br />

app/views/workflows/classify.html.erb
<div id="page">
  <div id="header">
    <h1><%= @workflow.name %></h1>
  </div>
  
  <%= render :partial => 'shared/flash', :locals => { :flash => flash } %>
  
  <div id="classify_subject">
    <%- session[:current_subject_locations].each do |location| %>
      <%= image_tag location %>
    <% end -%>
  </div>
  
  <div id="question_container">
    <div id="question">
      <%= render :partial => 'question' %>
    </div>
    
    <div id="answers">
      <%= render :partial => 'answers' %>
    </div>
    
    <div id="history">
      <%= render :partial => 'history' %>
    </div>
    
    <%- if current_zooniverse_user %>
      <div id="favourite">
        <%= render :partial => 'favourite' %>
      </div>
    <% end -%>
  </div>
</div>

app/views/workflows/next_task_or_end.js.erb
<% if @workflow_task %>
	$('#question').html('<%= escape_javascript render :partial => "question" %>');
	$('#answers').html('<%= escape_javascript render :partial => "answers" %>');
	$('#history').html('<%= escape_javascript render :partial => "history" %>');
<% else %>
	location = '/classify';
<% end %>

app/views/workflows/rewind.js.erb
$('#question').html('<%= escape_javascript render :partial => "question" %>');
$('#answers').html('<%= escape_javascript render :partial => "answers" %>');
$('#history').html('<%= escape_javascript render :partial => "history" %>');